name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Building
        working-directory: ./aplicacao
        run: docker-compose up -d
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Building
        working-directory: ./aplicacao
        run: docker-compose up -d

      - name: Reseting database
        working-directory: ./aplicacao
        run: docker-compose run app rails db:reset
        
      - name: Testing
        working-directory: ./aplicacao
        run: docker-compose run app rspec
    
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Running Lint
        working-directory: ./aplicacao
        run: docker-compose run app bash -c "gem install rubocop; rubocop --fail-level F"